# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'image_match.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(769, 581)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.load_image_button = QtWidgets.QPushButton(self.centralwidget)
        self.load_image_button.setGeometry(QtCore.QRect(110, 420, 113, 32))
        self.load_image_button.setObjectName("load_image_button")
        self.match_image_button = QtWidgets.QPushButton(self.centralwidget)
        self.match_image_button.setGeometry(QtCore.QRect(530, 420, 113, 32))
        self.match_image_button.setObjectName("match_image_button")
        self.MessageLabel = QtWidgets.QLabel(self.centralwidget)
        self.MessageLabel.setGeometry(QtCore.QRect(300, 350, 181, 41))
        self.MessageLabel.setText("")
        self.MessageLabel.setObjectName("MessageLabel")
        self.HeaderLabel = QtWidgets.QLabel(self.centralwidget)
        self.HeaderLabel.setGeometry(QtCore.QRect(330, 10, 121, 41))
        self.HeaderLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.HeaderLabel.setObjectName("HeaderLabel")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setGeometry(QtCore.QRect(29, 79, 711, 251))
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.main_frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 691, 231))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.original_image = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.original_image.setText("")
        self.original_image.setObjectName("original_image")
        self.horizontalLayout.addWidget(self.original_image)
        self.divider_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.divider_label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.divider_label.setText("")
        self.divider_label.setObjectName("divider_label")
        self.horizontalLayout.addWidget(self.divider_label)
        self.new_image = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.new_image.setText("")
        self.new_image.setObjectName("new_image")
        self.horizontalLayout.addWidget(self.new_image)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 769, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.load_image_button.setText(_translate("MainWindow", "Load Image"))
        self.match_image_button.setText(_translate("MainWindow", "Match Images"))
        self.HeaderLabel.setText(_translate("MainWindow", "IMAGE MATCHING"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
